[[procedure]]
name = "pull-deploy"
description = "Pulls stack-repo, deploys stacks"

[[procedure.config.stage]]
name = "Pull Repo"
executions = [
  { execution.type = "PullRepo", execution.params.pattern = "stack-repo" },
]

[[procedure.config.stage]]
name = "Deploy if changed"
executions = [
  # Uses the Batch version, witch matches many stacks by pattern
  # This one matches all stacks prefixed with `foo-` (wildcard) and `bar-` (regex).
  { execution.type = "BatchDeployStackIfChanged", execution.params.pattern = "auth" },
]