api:
  dashboard: true
  insecure: true
  debug: false

entryPoints:
  traefik:
    address: ":8080"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: emu.sh
            sans:
              - "*.emu.sh"
  traefik:
    address :"8080"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    # exposedByDefault: false
    # network: frontend # Optional; Only use the "proxy" Docker network, even if containers are on multiple networks.
certificatesResolvers:
  cloudflare:
    certificatesResolvers:
      email: alice@askalice.me
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        delaybeforecheck: 0
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        disablePropagationCheck: true
