version: '3.1'

services:
  collector:
    container_name: search-collector
    image: otel/opentelemetry-collector-contrib-dev:latest
    # network_mode: host
    #    image: otel/opentelemetry-collector:latest
    command: ['--config=/conf/collector-config.yaml']
    volumes:
      - ./etc/collector-config.yaml:/conf/collector-config.yaml
    ports:
      - '9464:9464'
      - '4317:4317'
      - '4318:4318'
      - '14268:14268'
      - '1888:1888' # pprof extension
      - '8888:8888' # Prometheus metrics exposed by the collector
      - '8889:8889' # Prometheus exporter metrics
      - '13133:13133' # health_check extension
      - '55670:55679' # zpages extension

  tempo:
    container_name: search-tempo
    image: grafana/tempo:1.5.0
    command: ['-config.file=/etc/tempo.yaml']
    volumes:
      - ./etc/tempo-local.yaml:/etc/tempo.yaml
      - ./data/tempo-data:/tmp/tempo
    ports:
      - '14269:14268' # jaeger ingest, Jaeger - Thrift HTTP
      - '14251:14250' # Jaeger - GRPC
      - '55680' # OpenTelemetry
      - '4319:4317' # OTLP GRPC
      - '4320:4318' # OTLP HTTP
      - '3100' # tempo
      - '6831/udp' # Jaeger - Thrift Compact
      - '6832/udp' # Jaeger - Thrift Binary
  promtail:
    container_name: search-promtail
    image: grafana/promtail:2.2.1
    command: -config.file=/etc/promtail/promtail.yaml
    volumes:
      - ./etc/promtail.yaml:/etc/promtail/promtail.yaml
      - ./data/logs:/app/logs
    depends_on:
      - loki
  volume_exporter:
    container_name: search-volume_exporter
    image: mnadeem/volume_exporter
    command: ['--volume-dir=tempo:/tmp/tempo', '--volume-dir=logs:/app/logs', '--volume-dir=loki:/tmp/loki']
    volumes:
      - ./data/logs:/app/logs
      - ./data/tempo-data:/tmp/tempo
      - ./data/loki-data:/tmp/loki
    ports:
      - 9889:9888
  prometheus:
    container_name: search-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - '9090:9090'

  grafana:
    container_name: search-grafana
    image: grafana/grafana:9.1.1-ubuntu
    volumes:
      - ./data/grafana-data/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana-data/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./data/grafana-data/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - '3002:3000'
    restart: always
    env_file:
      - .env
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.emu.sh`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3002"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
    depends_on:
      - prometheus
      - tempo
      - loki
      - volume_exporter
  loki:
    image: grafana/loki
    container_name: search-loki
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://collector:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - 3101:3100
    volumes:
      - ./etc/loki-local.yaml:/etc/loki/loki-config.yaml
      - ./data/loki-data:/tmp/loki
    command: -config.file=/etc/loki/loki-config.yaml
networks:
  traefik-public:
    external: true